### ISSUE TITLE
Using file-like objects to open HDF files

### ISSUE THREAD

**Issue by betolink** [silx-kit/jupyterlab-h5web#102]
**Is your feature request related to a problem? Please describe.**
Is is possible to open URLs instead of file paths? and if this is complicated what about using file-like objects?

**Describe the solution you'd like** 
Packages like fsspec allows us to open remote file as they were local and it would be very useful if this library could accept a file-like object to visualize HDF e.g.

```python
with open("file.hdf5") as f:
    H5Web(f)
```
one of the advantages is that we could use fsspec to open a remote file that's compressed and cache it locally so potentially we won't need to download the whole content. 

**Describe alternatives you've considered** 

**Additional context**

**Comment by loichuder** [comment]
Hello @betolink, thanks for the feedback

`jupyterlab-h5web` needs to do some back and forth between front and back-end to get data and metadata. To use a file object, this means the file object should be somehow serialized to be passed around and that we have less control on the opening/closing of the file. Unfortunately, this seems difficult and brittle. I will make some tests though.

On the other hand, I could imagine that URLs could be used instead of file paths. Not too sure. If you are not bound to the notebook, you may also be interested in https://myhdf5.hdfgroup.org/ that allows to browse remote files with H5Web.

**Comment by loichuder** [comment]
> On the other hand, I could imagine that URLs could be used instead of file paths. Not too sure.

Yeah after a bit of investigation, it seems to be the way to go. The back-end could be reworked a bit to use `h5pyd` or `fsspec` when supplying a URL to provide the same capabilities than for a local file.

Could you elaborate a bit on your usecase so that I can better understand ? Are you using `fsspec` to access remote HDF5/netCDF5 ? Do you have a sample code/file of your usage ?

**Comment by betolink** [comment]
Thanks for looking @loichuder! I think URLs would work too if there is a way to pass credentials for those HDF files behind auth walls (e.g. NASA data). This is why I originally thought of [fsspec](https://filesystem-spec.readthedocs.io/en/latest/features.html), with it we can handle caching, credentials, serialization, etc. (and yes, mainly for remote files)

```python

import fsspec

token = 'my-api-token'
fs = fsspec.HTTPFileSystem(
    headers={"Authorization": f"bearer {token}"}
)
with fs.open("file.hdf5") as f:
    H5Web(f)
```
This could happen in the back-end like you said and a user could only pass the URL and the request headers if required.

https://myhdf5.hdfgroup.org/ looks great but in our context we are accessing the HDF files from Jupyterlab, this is why this extension is so amazing!!

**Comment by loichuder** [comment]
Yeah, you are right: the config would have to be also passed down to the backend. This makes things a bit more complicated that what I originally thought.

Just for curiosity, have you tried [jupyter-fs](https://github.com/jpmorganchase/jupyter-fs) to access your remote files ? 

I have this naive thought is that `jupyter-fs` could handle the remote stuff transparently for `jupyterlab-h5web`. But that seems too good to be true :smile:

**Comment by loichuder** [comment]
This seems hard to achieve in the current status and I no longer have the bandwidth to work on this, sorry.
