### ISSUE TITLE
Custom selection of dimensions to be plotted

### ISSUE THREAD

**Issue by freiburgermsu** [silx-kit/jupyterlab-h5web#107]
Hello!

My group is interested to explore an H5 dataset through plotting various dimensions across each other. Your JupyterLab plugin interface is awesome, but we cannot seem select our own dimensions to plot. Can your plugin accommodate selecting data dimensions for plotting, or can the code be expanded to add this functionality?

Andrew

**Comment by loichuder** [comment]
Getting back to this after a long time, sorry.

> Can your plugin accommodate selecting data dimensions for plotting, or can the code be expanded to add this functionality?

We support the NeXus standard where metadata can be added to the file to define plottable data: https://manual.nexusformat.org/datarules.html#find-plottable-data. In essence, this means adding structure and attributes to the HDF5 groups/datasets that is then interpreted by H5Web to generate the plot.

The [example notebook](https://github.com/silx-kit/jupyterlab-h5web/blob/a088c94e34fd6150a3c7dec934c1ee0b3c4bb5ff/example.ipynb) shows an example of NeXus data generation.

We don't really plan to go beyond that since there are already many amazing tools to do customizable plots in Jupyter (matplotlib, bokeh, plotly). The advantage of the integration in Jupyter ecosystem is that you can use those directly by using `h5py` to get the data from the HDF5 file.

**Comment by loichuder** [comment]
Closing this. Can be reopened if needed.
