### ISSUE TITLE
State is shared among tabs

### ISSUE THREAD

**Issue by loichuder** [silx-kit/jupyterlab-h5web#20]
Toolbar controls are shared among JupyterLab tabs, even if they display different files.

**Comment by loichuder** [comment]
See https://github.com/silx-kit/h5web/issues/518

**Comment by loichuder** [comment]
Some progress was implemented in v0.0.7 but after some tests, this does not seem fully solved.

Also see https://github.com/silx-kit/h5web/issues/608

**Comment by axelboc** [comment]
Some quick thoughts so we can decide how to move forward:

### Demo app

- store can be global and initialised before render
- persist during use with global ID

### JupyterLab tabs

- store cannot be global
  - => one store per tab (or single store managing multiple sub-stores?)
- one tab can be persisted, but others cannot
- code not controlled by user, so no way to customise/configure anything
  - => detect if a tab is already open and disable persistence in any new tab
  - => OR rehydrate tabs on open and persist on close
  - => OR rehydrate tabs on open and persist anything

### Jupyter notebook cells

- store cannot be global
- one store per cell (or single store managing multiple sub-stores?)
- code controlled by user
  - => "save slots": provide store persistence ID when opening a cell
  - => OR provide API to pass initial state and persist on demand

**Comment by axelboc** [comment]
### Proposed solution

Global config provider exposed through `@h5web/app`:

```ts
<ConfigProvider>
  <App>
</ConfigProvider>
```

Global config provider wraps app with every toolbar config provider:

```ts
<LineConfigProvider>
  <HeatmapConfigProvider>
    {children}
  </HeatmapConfigProvider>
</LineConfigProvider>
```

Each toolbar config provider initialises its store on mount and provides it through context. It waits for the store to be rehydrated before rendering.

Two props are passed down from the global provider to the toolbar providers:
- a string prop called `id`-- if provided, the ID is appended to the stores' names (e.g. `h5web:<line|heatmap>:<id>`) in order to create new persistence slots in `localStorage`;
- a boolean prop called `rehydrateWithId`, which defaults to `false` -- if `false`, the store is rehydrated from the default persistence slots (`h5web:line`, `h5web:heatmap) instead of from the ID-suffixed slots.

---

### From `jupyterlab-h5web`'s side

- When opening H5Web in a JupyterLab tab or notebook cell for the first time, the extension should not pass any prop to `ConfigProvider`.
- When opening more tabs or cells, the extension should pass the `id` prop and let `rehydratedWithId` default to `false`. The `id` should be an incremental number (converted to string).
- When opening cells, the extension should allow users to pass the `id` and `rehydrateWithId` props themselves. By passing a custom `id` and setting `rehydrateWithId` to `true`, users can therefore create and/or re-use custom persistence slots in notebook cells.

**Comment by loichuder** [comment]
Thanks for the well-thought-out summary !

I think **Solution 2 for persistence** is promising: 
- it is not only simpler but more user-friendly
- there is no need to act directly on `ConfigProvider`: it can stay in the `App` so we don't need to change the current implementation.
- It matches my view of the store handling. To me, each h5web instance (whether it is a cell or a tab) should have its own store that is initialized from local storage. The instances' stores should not be interacting with each other (i.e. no persistence) during use.

**Comment by axelboc** [comment]
In https://github.com/silx-kit/h5web/pull/575 we started injecting stores via context, but we put the providers in the `Visualizer`, which meant that the stores were being recreated and rehydrated from `localStorage` every time the active visualization changed.

In https://github.com/silx-kit/h5web/pull/646, we move the providers higher up in the tree so the stores are created and rehydrated from `localStorage` only once. Here is an example of what this will look like in JupyterLab:

1. `localStorage` has Viridis color map and Log scale
2. User opens a file in two separate tabs (1 and 2).
3. User selects Inferno color map in tab 1 => `localStorage` now has Inferno+Log
4. User switches to tab 2 => toolbar still shows Viridis+Log, because the two tabs don't share the same store instances
5. User switches to Line vis and back to Heatmap vis => toolbar still shows Viridis+Log, because store was not rehydrated from `localStorage`.
6. User selects Linear scale => `localStorage` now has Viridis+Linear (color scale gets overridden)

We think this behaviour is satisfactory and that neither solution 1 nor 2 is needed in the end.

**Comment by loichuder** [comment]
I tried and it works great ! 

To sum up:
- Settings of open tabs can be changed independently as they have their own store instance
- Changes in any tab will change the user preferences in `localStorage`
- A new tab will have the settings set to user preferences (i.e. the last settings set) as the store is rehydrated from the `localStorage`
