### ISSUE TITLE
Issue with `+` in filename

### ISSUE THREAD

**Issue by t20100** [silx-kit/jupyterlab-h5web#45]
Running `H5Web("new_file+d.h5")` from a notebook leads to opening "new_file d.h5" on the server side (its already changed in the GET request).

Logs on the server side:
```
    Traceback (most recent call last):
      File "lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "lib/python3.8/site-packages/jupyterlab_h5web/handlers.py", line 25, in get
        with h5py.File(as_absolute_path(self.base_dir, Path(file_path)), "r") as h5file:
      File "lib/python3.8/site-packages/h5py/_hl/files.py", line 424, in __init__
        fid = make_fid(name, mode, userblock_size,
      File "lib/python3.8/site-packages/h5py/_hl/files.py", line 190, in make_fid
        fid = h5f.open(name, flags, fapl=fapl)
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "h5py/h5f.pyx", line 96, in h5py.h5f.open
    OSError: Unable to open file (unable to open file: name = '/home/new_file d.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by t20100** [comment]
Probably need to use [quote_plus](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus)

**Comment by t20100** [comment]
Issue is also when opening h5web with a double click from the file browser.

**Comment by loichuder** [comment]
After thorough investigation, the espacing happens **when the request URL is parsed on the backend**. The culprit is tornado's [parse_qs_bytes](https://github.com/tornadoweb/tornado/blob/master/tornado/httputil.py#L382) that parses arguments expecting them to be URL-encoded.  

To avoid problems of this type in the future, we should ensure that the filename is encoded every time it roundtrips between the front-end and the back-end.

This means encoding should happen in the following situations:
- [ ] When passing the filename in argument of the `H5Web` widget. #46 may be the solution
- [ ] When double-clicking on a file in the filebrowser. This is probably handled directly by JupyterLab.
- [ ] When making GET requests in the `H5GroveProvider` with filename as arg. This must be fixed in h5web.

**Comment by loichuder** [comment]
Fixed by https://github.com/silx-kit/h5web/pull/774 and https://github.com/silx-kit/h5web/pull/781
