### ISSUE TITLE
Crashes reading a large file

### ISSUE THREAD

**Issue by jonwright** [silx-kit/jupyterlab-h5web#71]
I am assuming this is the project behind the wonderful thing I found yesterday that lets me browse hdf5 files in jupyterlab? It looks fantastic. I wish I could figure out how to select x and y axes for a plot? I always see data versus point number. The rest of the message is a bug report for how I seem to have broke something already (sorry!) :

### Describe the bug

jupyterlab crashes when reading large dataset, perhaps an out of memory error?

### To Reproduce

1 - Log into jupyter-slurm.esrf.fr with one single core and the lab interface
2 - Navigate to open : /data/id11/nanoscope/blc12407/id11/CeO2_38keV/CeO2_38keV_CeO2_rotation/CeO2_38keV_CeO2_rotation.h5
3 - open dataset /1.1/measurement/eiger : it displays 
4 - open dataset /1.1/measurement/fpico6 : it displays
5 - go back to /1.1/measurement/eiger : jupyterlab stops running
6 - all the other tabs and kernels appear to exit when jupyterlab fails

### Expected behaviour

In the worst case, a plugin would crash without taking down all of the other kernels. Ideally it would not crash.

Is there  a way to use hdf5 slice operations (maybe combined with fast histograms) so you only hold in memory what is going to be displayed on the screen (e.g. maximum data is a 2D image)? Then libhdf5 should manage the memory cache in some sensible way.

### Context

- OS: ubuntu20.04
- Browser: Chrome
- Version: 94.0.4606.81 
- JupyterLab version: 2.3.1 (ESRF slurm installation

<details><summary>Extension lists</summary>
This is based on a bit of guesswork as to what is actually running when I use jupyter-slurm : 
<pre>
jupyter-slurm:~ % /scisoft/users/jupyter/jupy38ubuntu/bin/jupyter labextension list
JupyterLab v2.3.1
Known labextensions:
   app dir: /home/esrf/jupyter/jupy38ubuntu/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyterlab-datawidgets v6.3.0  enabled  OK
        jupyterlab-h5web v0.0.10  enabled  OK
        k3d v2.9.3  enabled  OK
jupyter-slurm:~ % /scisoft/users/jupyter/jupy38ubuntu/bin/jupyter serverextension list
config dir: /home/esrf/jupyter/jupy38ubuntu/etc/jupyter
    jupyterlab_h5web  enabled 
    - Validating...
      jupyterlab_h5web  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.3.1 OK
    jupyterlab_hdf  enabled 
    - Validating...
      jupyterlab_hdf 0.5.1 OK
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK

</pre>
</details>

**Comment by andygotz** [comment]
@jonwright thanks for the +ve feedback.  

@loichuder thanks for the explanations.  It seems like we are missing a tool to do flexible viewing of Nexus files i.e. selecting what to display against what. AM I right to say that users have to build their own tool with a mixture of h5py and matplotlib for now? Does bragy address this?

**Comment by axelboc** [comment]
This is outside of the scope of Braggy, for sure. It's always possible to make a new GUI for this, but note that a solution to this problem is to generate a NeXus-compliant HDF5 file with external links to the relevant datasets, and then open this file in H5Web. Obviously not as practical as a GUI, but we could easily provide a Python utility to make generating this sort of file a breeze.

**Comment by t20100** [comment]
There is already some helpers to save `NXData`: [nexusformat](https://github.com/nexpy/nexusformat/) or [silx.io.nxdata.save_NXdata](http://www.silx.org/doc/silx/latest/modules/io/nxdata.html#silx.io.nxdata.save_NXdata).

Otherwise since this runs in a notebook, using `matplotlib` or any other plot library is probably best suited for tailored plots if not saved as `NXData`.

BTW, in `silx view`, there is a feature to create "virtual NXData" by dragging and dropping datasets as signal and axes, but to me it is a bit complex since one needs to know about NeXus to use it.

**Comment by loichuder** [comment]
Following on the crash issue, we have something in the works to solve it: https://github.com/silx-kit/h5web/issues/616#issuecomment-982734122

I will close this once this is shipped in a jupyterlab-h5web release.

**Comment by loichuder** [comment]
https://github.com/silx-kit/h5web/issues/616#issuecomment-982734122 was integrated in v0.1.0 that is now deployed in jupyter-slurm.
